// yearsAgo calculé par rapport à 2026. Trié du plus ancien au plus récent.
// `image` est optionnel : chemin relatif vers un fichier dans images/.
// Absent ou fichier manquant → le repère reste affiché sans image (dégradation silencieuse).
export const REPERES = [
  { yearsAgo: 13_800_000_000, label: "Big Bang", description: "Naissance de l'univers observable.", image: "images/big-bang.jpg" },
  { yearsAgo: 13_000_000_000, label: "Formation de la Voie lactée", description: "Notre galaxie prend forme.", image: "images/formation-voie-lactee.jpg" },
  { yearsAgo: 4_600_000_000, label: "Formation du Système solaire", description: "Le Soleil et les planètes se forment à partir d'un nuage de gaz et de poussière.", image: "images/formation-systeme-solaire.jpg" },
  { yearsAgo: 4_540_000_000, label: "Formation de la Terre", description: "Notre planète s'agrège.", image: "images/formation-terre.jpg" },
  { yearsAgo: 4_500_000_000, label: "Formation de la Lune", description: "Issue d'une collision entre la Terre et une protoplanète.", image: "images/formation-lune.jpg" },
  { yearsAgo: 4_000_000_000, label: "Apparition de l'eau liquide", description: "Les océans primitifs se forment.", image: "images/apparition-eau-liquide.jpg" },
  { yearsAgo: 3_800_000_000, label: "Première vie", description: "Les premières bactéries apparaissent.", image: "images/premiere-vie.jpg" },
  { yearsAgo: 2_400_000_000, label: "Grande Oxydation", description: "La photosynthèse enrichit l'atmosphère en oxygène.", image: "images/grande-oxydation.jpg" },
  { yearsAgo: 1_850_000_000, label: "Premiers eucaryotes", description: "Des cellules avec un noyau apparaissent.", image: "images/premiers-eucaryotes.jpg" },
  { yearsAgo: 600_000_000, label: "Premiers organismes multicellulaires", description: "La vie se complexifie.", image: "images/premiers-organismes-multicellulaires.jpg" },
  { yearsAgo: 541_000_000, label: "Explosion cambrienne", description: "Diversification rapide des formes de vie animale.", image: "images/explosion-cambrienne.jpg" },
  { yearsAgo: 375_000_000, label: "Sortie des eaux", description: "Les premiers tétrapodes s'aventurent hors de l'eau.", image: "images/sortie-des-eaux.jpg" },
  { yearsAgo: 240_000_000, label: "Apparition des dinosaures", description: "Ils domineront la Terre pendant plus de 150 millions d'années.", image: "images/apparition-dinosaures.jpg" },
  { yearsAgo: 200_000_000, label: "Apparition des mammifères", description: "De petits mammifères coexistent avec les dinosaures.", image: "images/apparition-mammiferes.jpg" },
  { yearsAgo: 150_000_000, label: "Apparition des oiseaux", description: "Descendants directs des dinosaures théropodes.", image: "images/apparition-oiseaux.jpg" },
  { yearsAgo: 66_000_000, label: "Extinction des dinosaures", description: "Un astéroïde percute la Terre près du Yucatán.", image: "images/extinction-dinosaures.jpg" },
  { yearsAgo: 55_000_000, label: "Premiers primates", description: "Nos lointains ancêtres apparaissent.", image: "images/premiers-primates.jpg" },
  { yearsAgo: 6_000_000, label: "Séparation humains / chimpanzés", description: "Nos lignées évolutives divergent.", image: "images/separation-humains-chimpanzes.jpg" },
  { yearsAgo: 2_400_000, label: "Premiers Homo", description: "Apparition du genre Homo, avec Homo habilis.", image: "images/premiers-homo.jpg" },
  { yearsAgo: 1_000_000, label: "Maîtrise du feu", description: "Un tournant pour l'alimentation et la survie.", image: "images/maitrise-du-feu.jpg" },
  { yearsAgo: 300_000, label: "Apparition d'Homo sapiens", description: "Notre espèce apparaît en Afrique.", image: "images/apparition-homo-sapiens.jpg" },
  { yearsAgo: 70_000, label: "Sortie d'Afrique", description: "Homo sapiens commence à peupler le reste du monde.", image: "images/sortie-afrique.jpg" },
  { yearsAgo: 12_000, label: "Invention de l'agriculture", description: "La révolution néolithique transforme les sociétés humaines.", image: "images/invention-agriculture.jpg" },
  { yearsAgo: 5_200, label: "Invention de l'écriture", description: "En Mésopotamie, avec les premiers systèmes cunéiformes.", image: "images/invention-ecriture.jpg" },
  { yearsAgo: 4_500, label: "Pyramides de Gizeh", description: "Construction de la grande pyramide de Khéops.", image: "images/pyramides-gizeh.jpg" },
  { yearsAgo: 2_779, label: "Fondation de Rome", description: "Selon la tradition, en 753 avant notre ère.", image: "images/fondation-rome.jpg" },
  { yearsAgo: 1_550, label: "Chute de l'Empire romain d'Occident", description: "Marque conventionnellement la fin de l'Antiquité.", image: "images/chute-empire-romain.jpg" },
  { yearsAgo: 586, label: "Invention de l'imprimerie", description: "Gutenberg révolutionne la diffusion du savoir.", image: "images/invention-imprimerie.jpg" },
  { yearsAgo: 237, label: "Révolution française", description: "Bouleversement politique et social majeur en Europe.", image: "images/revolution-francaise.jpg" },
  { yearsAgo: 57, label: "Premier pas sur la Lune", description: "Neil Armstrong marche sur la Lune en 1969.", image: "images/premier-pas-lune.jpg" },
  { yearsAgo: 0, label: "Aujourd'hui", description: "Le moment présent, point de départ de ce voyage.", image: "images/aujourdhui.jpg" },
];
