// yearsAgo calculé par rapport à 2026. Trié du plus ancien au plus récent.
// `slug` référence une illustration dans illustrations.js.
// `category` détermine la couleur du cadre : cosmos | earth | life | human.
export const REPERES = [
  { yearsAgo: 13_800_000_000, label: "Big Bang", description: "Naissance de l'univers observable.", slug: "big-bang", category: "cosmos" },
  { yearsAgo: 13_000_000_000, label: "Formation de la Voie lactée", description: "Notre galaxie prend forme.", slug: "formation-voie-lactee", category: "cosmos" },
  { yearsAgo: 4_600_000_000, label: "Formation du Système solaire", description: "Le Soleil et les planètes se forment à partir d'un nuage de gaz et de poussière.", slug: "formation-systeme-solaire", category: "cosmos" },
  { yearsAgo: 4_540_000_000, label: "Formation de la Terre", description: "Notre planète s'agrège.", slug: "formation-terre", category: "cosmos" },
  { yearsAgo: 4_500_000_000, label: "Formation de la Lune", description: "Issue d'une collision entre la Terre et une protoplanète.", slug: "formation-lune", category: "cosmos" },
  { yearsAgo: 4_000_000_000, label: "Apparition de l'eau liquide", description: "Les océans primitifs se forment.", slug: "apparition-eau-liquide", category: "earth" },
  { yearsAgo: 3_800_000_000, label: "Première vie", description: "Les premières bactéries apparaissent.", slug: "premiere-vie", category: "earth" },
  { yearsAgo: 2_400_000_000, label: "Grande Oxydation", description: "La photosynthèse enrichit l'atmosphère en oxygène.", slug: "grande-oxydation", category: "earth" },
  { yearsAgo: 1_850_000_000, label: "Premiers eucaryotes", description: "Des cellules avec un noyau apparaissent.", slug: "premiers-eucaryotes", category: "earth" },
  { yearsAgo: 600_000_000, label: "Premiers organismes multicellulaires", description: "La vie se complexifie.", slug: "premiers-organismes-multicellulaires", category: "earth" },
  { yearsAgo: 541_000_000, label: "Explosion cambrienne", description: "Diversification rapide des formes de vie animale.", slug: "explosion-cambrienne", category: "earth" },
  { yearsAgo: 375_000_000, label: "Sortie des eaux", description: "Les premiers tétrapodes s'aventurent hors de l'eau.", slug: "sortie-des-eaux", category: "earth" },
  { yearsAgo: 240_000_000, label: "Apparition des dinosaures", description: "Ils domineront la Terre pendant plus de 150 millions d'années.", slug: "apparition-dinosaures", category: "life" },
  { yearsAgo: 200_000_000, label: "Apparition des mammifères", description: "De petits mammifères coexistent avec les dinosaures.", slug: "apparition-mammiferes", category: "life" },
  { yearsAgo: 150_000_000, label: "Apparition des oiseaux", description: "Descendants directs des dinosaures théropodes.", slug: "apparition-oiseaux", category: "life" },
  { yearsAgo: 66_000_000, label: "Extinction des dinosaures", description: "Un astéroïde percute la Terre près du Yucatán.", slug: "extinction-dinosaures", category: "life" },
  { yearsAgo: 55_000_000, label: "Premiers primates", description: "Nos lointains ancêtres apparaissent.", slug: "premiers-primates", category: "life" },
  { yearsAgo: 6_000_000, label: "Séparation humains / chimpanzés", description: "Nos lignées évolutives divergent.", slug: "separation-humains-chimpanzes", category: "life" },
  { yearsAgo: 2_400_000, label: "Premiers Homo", description: "Apparition du genre Homo, avec Homo habilis.", slug: "premiers-homo", category: "human" },
  { yearsAgo: 1_000_000, label: "Maîtrise du feu", description: "Un tournant pour l'alimentation et la survie.", slug: "maitrise-du-feu", category: "human" },
  { yearsAgo: 300_000, label: "Apparition d'Homo sapiens", description: "Notre espèce apparaît en Afrique.", slug: "apparition-homo-sapiens", category: "human" },
  { yearsAgo: 70_000, label: "Sortie d'Afrique", description: "Homo sapiens commence à peupler le reste du monde.", slug: "sortie-afrique", category: "human" },
  { yearsAgo: 12_000, label: "Invention de l'agriculture", description: "La révolution néolithique transforme les sociétés humaines.", slug: "invention-agriculture", category: "human" },
  { yearsAgo: 5_200, label: "Invention de l'écriture", description: "En Mésopotamie, avec les premiers systèmes cunéiformes.", slug: "invention-ecriture", category: "human" },
  { yearsAgo: 4_500, label: "Pyramides de Gizeh", description: "Construction de la grande pyramide de Khéops.", slug: "pyramides-gizeh", category: "human" },
  { yearsAgo: 2_779, label: "Fondation de Rome", description: "Selon la tradition, en 753 avant notre ère.", slug: "fondation-rome", category: "human" },
  { yearsAgo: 1_550, label: "Chute de l'Empire romain d'Occident", description: "Marque conventionnellement la fin de l'Antiquité.", slug: "chute-empire-romain", category: "human" },
  { yearsAgo: 586, label: "Invention de l'imprimerie", description: "Gutenberg révolutionne la diffusion du savoir.", slug: "invention-imprimerie", category: "human" },
  { yearsAgo: 237, label: "Révolution française", description: "Bouleversement politique et social majeur en Europe.", slug: "revolution-francaise", category: "human" },
  { yearsAgo: 57, label: "Premier pas sur la Lune", description: "Neil Armstrong marche sur la Lune en 1969.", slug: "premier-pas-lune", category: "human" },
  { yearsAgo: 0, label: "Aujourd'hui", description: "Le moment présent, point de départ de ce voyage.", slug: "aujourdhui", category: "human" },
];
