export interface Item {
  id: string;
  nom: string;
  photo: string;
  prix: number;
  /** petite explication du prix (haut ou bas), affichée à la révélation */
  anecdote?: string;
}

const BASE = import.meta.env.BASE_URL;

export const ITEMS: Item[] = [
  {
    id: "ticket-metro-paris",
    nom: "Un ticket de métro à l'unité, à Paris",
    photo: `${BASE}photos/ca-coute-combien/ticket-metro-paris.webp`,
    prix: 2.15,
  },
  {
    id: "pizza-napoli",
    nom: "Une pizza margherita dans une pizzeria historique de Naples",
    photo: `${BASE}photos/ca-coute-combien/pizza-napoli.webp`,
    prix: 5,
  },
  {
    id: "big-mac",
    nom: "Un Big Mac, menu solo, en France",
    photo: `${BASE}photos/ca-coute-combien/big-mac.webp`,
    prix: 5.9,
  },
  {
    id: "cabane-arbre",
    nom: "Une nuit dans une cabane perchée dans les arbres",
    photo: `${BASE}photos/ca-coute-combien/cabane-arbre.webp`,
    prix: 180,
  },
  {
    id: "san-marco-cafe",
    nom: "Un café en terrasse sur la Piazza San Marco, à Venise",
    photo: `${BASE}photos/ca-coute-combien/san-marco-cafe.webp`,
    prix: 13,
    anecdote: "Le café ne vaut pas grand-chose : on paie la place, l'orchestre et cinq siècles de vue sur la basilique.",
  },
  {
    id: "icehotel",
    nom: "Une nuit dans une chambre de glace à l'Icehotel, en Suède",
    photo: `${BASE}photos/ca-coute-combien/icehotel.webp`,
    prix: 400,
    anecdote: "L'hôtel fond chaque printemps et se reconstruit chaque hiver, sculpté dans la glace de la rivière Torne.",
  },
  {
    id: "monaco-gp-tribune",
    nom: "Une place en tribune pour les 3 jours du Grand Prix de Monaco",
    photo: `${BASE}photos/ca-coute-combien/monaco-gp-tribune.webp`,
    prix: 990,
    anecdote: "Un circuit en pleine ville, le plus court du calendrier : très peu de tribunes, énormément de demande.",
  },
  {
    id: "truffe-alba",
    nom: "Une truffe blanche d'Alba, les 100 grammes en pleine saison",
    photo: `${BASE}photos/ca-coute-combien/truffe-alba.webp`,
    prix: 450,
    anecdote: "La truffe blanche ne se cultive pas : elle se trouve, au flair des chiens truffiers, quelques semaines par an.",
  },
  {
    id: "burj-al-arab",
    nom: "Une nuit dans la suite la moins chère du Burj Al Arab, à Dubaï",
    photo: `${BASE}photos/ca-coute-combien/burj-al-arab.webp`,
    prix: 1900,
    anecdote: "Il n'y a que des suites en duplex, avec majordome 24 h/24 — le fameux « 7 étoiles » est né du marketing.",
  },
  {
    id: "yacht-saint-tropez",
    nom: "Une journée de location d'un yacht à Saint-Tropez",
    photo: `${BASE}photos/ca-coute-combien/yacht-saint-tropez.webp`,
    prix: 3500,
  },
  {
    id: "ticket-eiffel-sommet",
    nom: "Un billet pour le sommet de la Tour Eiffel, à Paris",
    photo: `${BASE}photos/ca-coute-combien/ticket-eiffel-sommet.webp`,
    prix: 28.3,
  },
  {
    id: "boeuf-kobe",
    nom: "Une portion de bœuf de Kobe (200 g), au restaurant",
    photo: `${BASE}photos/ca-coute-combien/boeuf-kobe.webp`,
    prix: 180,
    anecdote: "L'appellation Kobe est ultra-protégée : quelques milliers de bêtes certifiées par an dans le monde.",
  },
  {
    id: "capsule-hotel-tokyo",
    nom: "Une nuit dans une capsule, dans un capsule hotel à Tokyo",
    photo: `${BASE}photos/ca-coute-combien/capsule-hotel-tokyo.webp`,
    prix: 35,
  },
  {
    id: "gondole-venise",
    nom: "Un tour en gondole à Venise (30 minutes)",
    photo: `${BASE}photos/ca-coute-combien/gondole-venise.webp`,
    prix: 90,
  },
  {
    id: "lego-minifigure",
    nom: "Une figurine Lego collector, à l'unité",
    photo: `${BASE}photos/ca-coute-combien/lego-minifigure.webp`,
    prix: 5,
  },
  {
    id: "champagne-dom-perignon",
    nom: "Une bouteille de champagne Dom Pérignon",
    photo: `${BASE}photos/ca-coute-combien/champagne-dom-perignon.webp`,
    prix: 190,
    anecdote: "Dom Pérignon n'existe qu'en millésime : seules les meilleures années, après huit ans de cave minimum.",
  },
  {
    id: "wimbledon-centre-court",
    nom: "Un billet en tribune pour un après-midi au Centre Court de Wimbledon",
    photo: `${BASE}photos/ca-coute-combien/wimbledon-centre-court.webp`,
    prix: 200,
  },
  {
    id: "montgolfiere-cappadoce",
    nom: "Un vol en montgolfière au lever du soleil, en Cappadoce",
    photo: `${BASE}photos/ca-coute-combien/montgolfiere-cappadoce.webp`,
    prix: 180,
  },
  {
    id: "rolex-submariner",
    nom: "Une montre Rolex Submariner, neuve en boutique",
    photo: `${BASE}photos/ca-coute-combien/rolex-submariner.webp`,
    prix: 9200,
    anecdote: "Le prix boutique est presque théorique : la production est limitée et les listes d'attente durent des années.",
  },
  {
    id: "colisee-rome",
    nom: "Un billet d'entrée au Colisée, à Rome",
    photo: `${BASE}photos/ca-coute-combien/colisee-rome.webp`,
    prix: 18,
  },
  {
    id: "huitres-brasserie",
    nom: "Une douzaine d'huîtres, au comptoir d'une brasserie parisienne",
    photo: `${BASE}photos/ca-coute-combien/huitres-brasserie.webp`,
    prix: 24,
  },
  {
    id: "louvre-pyramide",
    nom: "Un billet d'entrée au musée du Louvre, à Paris",
    photo: `${BASE}photos/ca-coute-combien/louvre-pyramide.webp`,
    prix: 22,
  },
  {
    id: "helico-manhattan",
    nom: "Un tour en hélicoptère de 15 minutes au-dessus de Manhattan",
    photo: `${BASE}photos/ca-coute-combien/helico-manhattan.webp`,
    prix: 230,
    anecdote: "L'heure de vol d'un hélicoptère coûte plus de 1 500 € : les 15 minutes se partagent entre passagers.",
  },
  {
    id: "cronut-nyc",
    nom: "Un cronut, à la boulangerie originale de New York",
    photo: `${BASE}photos/ca-coute-combien/cronut-nyc.webp`,
    prix: 6.5,
    anecdote: "Mi-croissant mi-donut, viral en 2013 : file d'attente dès l'aube et quota de deux par personne.",
  },
  {
    id: "sneakers-air-jordan",
    nom: "Une paire de sneakers Air Jordan 1, prix boutique",
    photo: `${BASE}photos/ca-coute-combien/sneakers-air-jordan.webp`,
    prix: 180,
    anecdote: "Le prix boutique est volontairement contenu : la rareté organisée fait exploser la revente, pas l'étiquette.",
  },
  {
    id: "plein-gpl",
    nom: "Un plein de GPL pour une citadine",
    photo: `${BASE}photos/ca-coute-combien/plein-gpl.webp`,
    prix: 30,
  },
  {
    id: "carte-grise-citadine",
    nom: "Une carte grise pour une citadine",
    photo: `${BASE}photos/ca-coute-combien/carte-grise-citadine.webp`,
    prix: 50,
  },
  {
    id: "ramonage-cheminee",
    nom: "Un ramonage de cheminée",
    photo: `${BASE}photos/ca-coute-combien/ramonage-cheminee.webp`,
    prix: 70,
  },
  {
    id: "place-creche-mois",
    nom: "Une place en crèche, un mois",
    photo: `${BASE}photos/ca-coute-combien/place-creche-mois.webp`,
    prix: 800,
    anecdote: "Une place coûte en réalité plus de 2 000 € par mois : collectivités et CAF absorbent la différence.",
  },
  {
    id: "defile-mode-place",
    nom: "Une place de spectateur à un défilé de mode",
    photo: `${BASE}photos/ca-coute-combien/defile-mode-place.webp`,
    prix: 500,
  },
  {
    id: "nuit-refuge-garde",
    nom: "Une nuitée en refuge de montagne gardé, demi-pension",
    photo: `${BASE}photos/ca-coute-combien/nuit-refuge-garde.webp`,
    prix: 60,
  },
  {
    id: "laverie-automatique-mois",
    nom: "Un usage régulier de laverie automatique, un mois",
    photo: `${BASE}photos/ca-coute-combien/laverie-automatique-mois.webp`,
    prix: 40,
  },
  {
    id: "reparation-ecran-smartphone",
    nom: "Une réparation d'écran de smartphone cassé",
    photo: `${BASE}photos/ca-coute-combien/reparation-ecran-smartphone.webp`,
    prix: 120,
  },
  {
    id: "demenagement-studio",
    nom: "Un déménagement pour un petit studio",
    photo: `${BASE}photos/ca-coute-combien/demenagement-studio.webp`,
    prix: 400,
  },
  {
    id: "consultation-osteopathe",
    nom: "Une consultation chez un ostéopathe",
    photo: `${BASE}photos/ca-coute-combien/consultation-osteopathe.webp`,
    prix: 60,
  },
  {
    id: "forfait-mobile-haut-gamme-mois",
    nom: "Un forfait mobile haut de gamme, un mois",
    photo: `${BASE}photos/ca-coute-combien/forfait-mobile-haut-gamme-mois.webp`,
    prix: 30,
  },
  {
    id: "cinema-4dx-place",
    nom: "Une place de cinéma en 4DX",
    photo: `${BASE}photos/ca-coute-combien/cinema-4dx-place.webp`,
    prix: 20,
  },
  {
    id: "nuit-yourte",
    nom: "Une nuit dans une yourte",
    photo: `${BASE}photos/ca-coute-combien/nuit-yourte.webp`,
    prix: 90,
  },
  {
    id: "conduite-accompagnee-forfait",
    nom: "Un forfait complet de conduite accompagnée",
    photo: `${BASE}photos/ca-coute-combien/conduite-accompagnee-forfait.webp`,
    prix: 1200,
    anecdote: "Une vingtaine d'heures avec moniteur et voiture à double commande : c'est de la main-d'œuvre, surtout.",
  },
  {
    id: "parking-sous-sol-mensuel",
    nom: "Un abonnement mensuel de parking en sous-sol, grande ville",
    photo: `${BASE}photos/ca-coute-combien/parking-sous-sol-mensuel.webp`,
    prix: 150,
  },
  {
    id: "box-streaming-sportif-mois",
    nom: "Un abonnement mensuel à une chaîne de streaming sportif",
    photo: `${BASE}photos/ca-coute-combien/box-streaming-sportif-mois.webp`,
    prix: 20,
  },
  {
    id: "carte-identite-renouvellement",
    nom: "Le renouvellement d'une carte d'identité",
    photo: `${BASE}photos/ca-coute-combien/carte-identite-renouvellement.webp`,
    prix: 25,
  },
  {
    id: "timbre-lettre-prioritaire",
    nom: "Un timbre pour une lettre prioritaire",
    photo: `${BASE}photos/ca-coute-combien/timbre-lettre-prioritaire.webp`,
    prix: 1.5,
  },
  {
    id: "amende-stationnement-genant",
    nom: "Une amende pour stationnement gênant",
    photo: `${BASE}photos/ca-coute-combien/amende-stationnement-genant.webp`,
    prix: 135,
    anecdote: "Montant fixé par décret, identique dans toute la France — pas de négociation possible.",
  },
  {
    id: "sac-pellets-poele",
    nom: "Un sac de granulés de bois (pellets) pour poêle",
    photo: `${BASE}photos/ca-coute-combien/sac-pellets-poele.webp`,
    prix: 6,
  },
  {
    id: "detartrage-dentiste",
    nom: "Un détartrage chez le dentiste",
    photo: `${BASE}photos/ca-coute-combien/detartrage-dentiste.webp`,
    prix: 50,
  },
  {
    id: "data-illimitee-etranger-semaine",
    nom: "Un forfait data illimité à l'étranger, une semaine",
    photo: `${BASE}photos/ca-coute-combien/data-illimitee-etranger-semaine.webp`,
    prix: 40,
  },
  {
    id: "salon-professionnel-place",
    nom: "Une entrée à un salon professionnel",
    photo: `${BASE}photos/ca-coute-combien/salon-professionnel-place.webp`,
    prix: 15,
  },
  {
    id: "revision-complete-voiture",
    nom: "Une révision complète de voiture chez un garagiste",
    photo: `${BASE}photos/ca-coute-combien/revision-complete-voiture.webp`,
    prix: 250,
  },
  {
    id: "ps5",
    nom: "Une console PlayStation 5",
    photo: `${BASE}photos/ca-coute-combien/ps5.webp`,
    prix: 550,
  },
  {
    id: "velo-electrique",
    nom: "Un vélo électrique",
    photo: `${BASE}photos/ca-coute-combien/velo-electrique.webp`,
    prix: 1200,
  },
  {
    id: "skis-complets",
    nom: "Une paire de skis complète (équipement)",
    photo: `${BASE}photos/ca-coute-combien/skis-complets.webp`,
    prix: 500,
  },
  {
    id: "drone-dji-mini",
    nom: "Un drone grand public (type DJI Mini)",
    photo: `${BASE}photos/ca-coute-combien/drone-dji-mini.webp`,
    prix: 500,
  },
  {
    id: "laptop-milieu-gamme",
    nom: "Un ordinateur portable milieu de gamme",
    photo: `${BASE}photos/ca-coute-combien/laptop-milieu-gamme.webp`,
    prix: 800,
  },
  {
    id: "apple-watch",
    nom: "Une montre connectée Apple Watch",
    photo: `${BASE}photos/ca-coute-combien/apple-watch.webp`,
    prix: 400,
  },
  {
    id: "paris-new-york-eco",
    nom: "Un aller-retour Paris-New York en classe économique",
    photo: `${BASE}photos/ca-coute-combien/paris-new-york-eco.webp`,
    prix: 600,
  },
  {
    id: "chambre-vue-tour-eiffel",
    nom: "Une nuit dans une chambre avec vue sur la tour Eiffel",
    photo: `${BASE}photos/ca-coute-combien/chambre-vue-tour-eiffel.webp`,
    prix: 350,
  },
  {
    id: "cours-golf-pro",
    nom: "Un cours de golf avec un professionnel",
    photo: `${BASE}photos/ca-coute-combien/cours-golf-pro.webp`,
    prix: 70,
  },
  {
    id: "combinaison-plongee",
    nom: "Une combinaison de plongée complète",
    photo: `${BASE}photos/ca-coute-combien/combinaison-plongee.webp`,
    prix: 400,
  },
  {
    id: "montgolfiere-loire",
    nom: "Un survol en montgolfière au-dessus de la Loire",
    photo: `${BASE}photos/ca-coute-combien/montgolfiere-loire.webp`,
    prix: 220,
  },
  {
    id: "opera-paris-place",
    nom: "Une place standard à l'Opéra de Paris",
    photo: `${BASE}photos/ca-coute-combien/opera-paris-place.webp`,
    prix: 90,
  },
  {
    id: "guitare-electrique-entree",
    nom: "Une guitare électrique d'entrée de gamme",
    photo: `${BASE}photos/ca-coute-combien/guitare-electrique-entree.webp`,
    prix: 300,
  },
  {
    id: "velo-course-carbone",
    nom: "Un vélo de course en carbone",
    photo: `${BASE}photos/ca-coute-combien/velo-course-carbone.webp`,
    prix: 2500,
  },
  {
    id: "tondeuse-robot",
    nom: "Une tondeuse à gazon robot",
    photo: `${BASE}photos/ca-coute-combien/tondeuse-robot.webp`,
    prix: 900,
  },
  {
    id: "sac-chanel-classique",
    nom: "Un sac à main Chanel classique",
    photo: `${BASE}photos/ca-coute-combien/sac-chanel-classique.webp`,
    prix: 8000,
  },
  {
    id: "louboutin",
    nom: "Une paire d'escarpins Louboutin",
    photo: `${BASE}photos/ca-coute-combien/louboutin.webp`,
    prix: 800,
  },
  {
    id: "costume-sur-mesure",
    nom: "Un costume sur mesure chez un tailleur parisien",
    photo: `${BASE}photos/ca-coute-combien/costume-sur-mesure.webp`,
    prix: 2000,
  },
  {
    id: "rolex-daytona",
    nom: "Une Rolex Daytona",
    photo: `${BASE}photos/ca-coute-combien/rolex-daytona.webp`,
    prix: 35000,
  },
  {
    id: "iphone-pro-max-top",
    nom: "Un iPhone Pro Max, version la plus chère",
    photo: `${BASE}photos/ca-coute-combien/iphone-pro-max-top.webp`,
    prix: 1500,
  },
  {
    id: "suite-presidentielle-palace",
    nom: "Une nuit dans la suite présidentielle d'un palace parisien",
    photo: `${BASE}photos/ca-coute-combien/suite-presidentielle-palace.webp`,
    prix: 15000,
  },
  {
    id: "dejeuner-3-etoiles-michelin",
    nom: "Un dîner dans un restaurant 3 étoiles Michelin",
    photo: `${BASE}photos/ca-coute-combien/dejeuner-3-etoiles-michelin.webp`,
    prix: 400,
  },
  {
    id: "whisky-japonais-rare",
    nom: "Une bouteille de whisky japonais rare",
    photo: `${BASE}photos/ca-coute-combien/whisky-japonais-rare.webp`,
    prix: 2000,
  },
  {
    id: "hermes-birkin",
    nom: "Un sac Hermès Birkin",
    photo: `${BASE}photos/ca-coute-combien/hermes-birkin.webp`,
    prix: 12000,
  },
  {
    id: "tesla-model-s",
    nom: "Une Tesla Model S",
    photo: `${BASE}photos/ca-coute-combien/tesla-model-s.webp`,
    prix: 90000,
  },
  {
    id: "site-lancement-spatial-prive",
    nom: "La construction d'un site de lancement spatial privé",
    photo: `${BASE}photos/ca-coute-combien/site-lancement-spatial-prive.webp`,
    prix: 800000000,
  },
  {
    id: "vin-plus-cher-encheres",
    nom: "La bouteille de vin la plus chère jamais vendue aux enchères",
    photo: `${BASE}photos/ca-coute-combien/vin-plus-cher-encheres.webp`,
    prix: 500000,
  },
  {
    id: "timbre-poste-rarissime",
    nom: "Le timbre-poste le plus cher au monde",
    photo: `${BASE}photos/ca-coute-combien/timbre-poste-rarissime.webp`,
    prix: 8000000,
  },
  {
    id: "patek-philippe-complication",
    nom: "Une montre Patek Philippe, grande complication",
    photo: `${BASE}photos/ca-coute-combien/patek-philippe-complication.webp`,
    prix: 250000,
  },
  {
    id: "aigle-royal-fauconnerie",
    nom: "Un aigle royal dressé pour la fauconnerie, élevage légal",
    photo: `${BASE}photos/ca-coute-combien/aigle-royal-fauconnerie.webp`,
    prix: 8000,
  },
  {
    id: "domaine-viticole-bourgogne",
    nom: "Un domaine viticole en Bourgogne, grand cru classé",
    photo: `${BASE}photos/ca-coute-combien/domaine-viticole-bourgogne.webp`,
    prix: 25000000,
  },
  {
    id: "billet-blue-origin",
    nom: "Un billet complet pour un vol touristique Blue Origin",
    photo: `${BASE}photos/ca-coute-combien/billet-blue-origin.webp`,
    prix: 450000,
    anecdote: "Environ dix minutes de vol pour trois minutes d'apesanteur — le prix de la minute est vertigineux.",
  },
  {
    id: "yacht-voile-americas-cup",
    nom: "Un yacht de compétition America's Cup, à l'unité",
    photo: `${BASE}photos/ca-coute-combien/yacht-voile-americas-cup.webp`,
    prix: 6000000,
  },
  {
    id: "studio-enregistrement-pro",
    nom: "Un studio d'enregistrement professionnel complet",
    photo: `${BASE}photos/ca-coute-combien/studio-enregistrement-pro.webp`,
    prix: 200000,
  },
  {
    id: "collection-tintin-premiere",
    nom: "Une collection de bandes dessinées Tintin, première édition",
    photo: `${BASE}photos/ca-coute-combien/collection-tintin-premiere.webp`,
    prix: 50000,
  },
  {
    id: "jet-ski-neuf",
    nom: "Un jet-ski neuf",
    photo: `${BASE}photos/ca-coute-combien/jet-ski-neuf.webp`,
    prix: 12000,
  },
  {
    id: "caravane-luxe-equipee",
    nom: "Une caravane de luxe tout équipée",
    photo: `${BASE}photos/ca-coute-combien/caravane-luxe-equipee.webp`,
    prix: 60000,
  },
  {
    id: "traineau-chiens-excursion",
    nom: "Une excursion en traîneau à chiens, une journée",
    photo: `${BASE}photos/ca-coute-combien/traineau-chiens-excursion.webp`,
    prix: 150,
  },
  {
    id: "cabane-pilotis-lagon",
    nom: "Une nuit dans une cabane sur pilotis au-dessus d'un lagon",
    photo: `${BASE}photos/ca-coute-combien/cabane-pilotis-lagon.webp`,
    prix: 500,
  },
  {
    id: "club-tennis-prive-annuel",
    nom: "Un abonnement annuel à un club de tennis privé",
    photo: `${BASE}photos/ca-coute-combien/club-tennis-prive-annuel.webp`,
    prix: 2500,
  },
  {
    id: "gants-boxe-signes",
    nom: "Des gants de boxe professionnels signés",
    photo: `${BASE}photos/ca-coute-combien/gants-boxe-signes.webp`,
    prix: 800,
  },
  {
    id: "maillot-star-encheres",
    nom: "Un maillot de football porté en match par une star, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/maillot-star-encheres.webp`,
    prix: 50000,
  },
  {
    id: "ballon-foot-officiel-cdm",
    nom: "Un ballon de football officiel de Coupe du Monde",
    photo: `${BASE}photos/ca-coute-combien/ballon-foot-officiel-cdm.webp`,
    prix: 150,
  },
  {
    id: "raquette-champion-encheres",
    nom: "Une raquette de tennis utilisée par un champion, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/raquette-champion-encheres.webp`,
    prix: 15000,
  },
  {
    id: "velo-bmx-pro",
    nom: "Un vélo BMX professionnel",
    photo: `${BASE}photos/ca-coute-combien/velo-bmx-pro.webp`,
    prix: 900,
  },
  {
    id: "planche-surf-mesure",
    nom: "Une planche de surf sur mesure",
    photo: `${BASE}photos/ca-coute-combien/planche-surf-mesure.webp`,
    prix: 700,
  },
  {
    id: "kayak-mer-carbone",
    nom: "Un kayak de mer en fibre de carbone",
    photo: `${BASE}photos/ca-coute-combien/kayak-mer-carbone.webp`,
    prix: 3000,
  },
  {
    id: "tente-glamping-equipee",
    nom: "Une tente de glamping tout équipée",
    photo: `${BASE}photos/ca-coute-combien/tente-glamping-equipee.webp`,
    prix: 8000,
  },
  {
    id: "machine-espresso-pro",
    nom: "Une machine à espresso professionnelle italienne",
    photo: `${BASE}photos/ca-coute-combien/machine-espresso-pro.webp`,
    prix: 2000,
  },
  {
    id: "piano-queue-concert",
    nom: "Un piano à queue de concert",
    photo: `${BASE}photos/ca-coute-combien/piano-queue-concert.webp`,
    prix: 80000,
    anecdote: "Près d'un an de fabrication artisanale et 12 000 pièces assemblées à la main.",
  },
  {
    id: "caviar-beluga",
    nom: "Un caviar béluga, les 30 grammes",
    photo: `${BASE}photos/ca-coute-combien/caviar-beluga.webp`,
    prix: 280,
    anecdote: "L'esturgeon béluga met quinze à vingt ans avant de produire ses premiers œufs.",
  },
  {
    id: "foie-gras-entier",
    nom: "Un foie gras de canard entier mi-cuit (400 g)",
    photo: `${BASE}photos/ca-coute-combien/foie-gras-entier.webp`,
    prix: 45,
  },
  {
    id: "jambon-iberique-bellota",
    nom: "Un jambon ibérique de bellota entier (pata negra)",
    photo: `${BASE}photos/ca-coute-combien/jambon-iberique-bellota.webp`,
    prix: 450,
  },
  {
    id: "safran-gramme",
    nom: "Un gramme de safran en filaments",
    photo: `${BASE}photos/ca-coute-combien/safran-gramme.webp`,
    prix: 12,
    anecdote: "Il faut cueillir à la main environ 150 fleurs de crocus pour un seul gramme : l'épice la plus chère du monde.",
  },
  {
    id: "vanille-madagascar",
    nom: "100 grammes de gousses de vanille de Madagascar",
    photo: `${BASE}photos/ca-coute-combien/vanille-madagascar.webp`,
    prix: 120,
    anecdote: "Chaque fleur de vanillier est pollinisée à la main, une par une, puis la gousse sèche pendant des mois.",
  },
  {
    id: "melon-yubari",
    nom: "Une caisse de melons Yubari King, prix courant au Japon",
    photo: `${BASE}photos/ca-coute-combien/melon-yubari.webp`,
    prix: 130,
    anecdote: "Au Japon, c'est un fruit-cadeau : calibrage parfait, peau immaculée — les plus beaux partent aux enchères.",
  },
  {
    id: "mangue-miyazaki",
    nom: 'Une mangue Miyazaki "Taiyo no Tamago", la pièce',
    photo: `${BASE}photos/ca-coute-combien/mangue-miyazaki.webp`,
    prix: 45,
    anecdote: "Cultivée en serre, suspendue dans un filet pour mûrir sans toucher quoi que ce soit.",
  },
  {
    id: "the-matcha-ceremonial",
    nom: "100 grammes de thé matcha cérémonial haut de gamme",
    photo: `${BASE}photos/ca-coute-combien/the-matcha-ceremonial.webp`,
    prix: 45,
  },
  {
    id: "cafe-kopi-luwak",
    nom: "100 grammes de café Kopi Luwak",
    photo: `${BASE}photos/ca-coute-combien/cafe-kopi-luwak.webp`,
    prix: 80,
    anecdote: "Les grains sont digérés puis rejetés par une civette : rareté réelle, éthique très discutée.",
  },
  {
    id: "cognac-louis-xiii",
    nom: "Une bouteille de cognac Louis XIII de Rémy Martin",
    photo: `${BASE}photos/ca-coute-combien/cognac-louis-xiii.webp`,
    prix: 3000,
    anecdote: "Un assemblage d'eaux-de-vie dont certaines ont un siècle, servi dans une carafe en cristal.",
  },
  {
    id: "sake-junmai-premium",
    nom: "Une bouteille de saké japonais haut de gamme (junmai)",
    photo: `${BASE}photos/ca-coute-combien/sake-junmai-premium.webp`,
    prix: 150,
  },
  {
    id: "absinthe-artisanale",
    nom: "Une bouteille d'absinthe artisanale",
    photo: `${BASE}photos/ca-coute-combien/absinthe-artisanale.webp`,
    prix: 60,
  },
  {
    id: "huile-olive-grand-cru",
    nom: "Une bouteille de 500 ml d'huile d'olive grand cru",
    photo: `${BASE}photos/ca-coute-combien/huile-olive-grand-cru.webp`,
    prix: 35,
  },
  {
    id: "homard-thermidor",
    nom: "Un homard thermidor, au restaurant",
    photo: `${BASE}photos/ca-coute-combien/homard-thermidor.webp`,
    prix: 55,
  },
  {
    id: "fleur-sel-guerande",
    nom: "500 grammes de fleur de sel de Guérande AOP",
    photo: `${BASE}photos/ca-coute-combien/fleur-sel-guerande.webp`,
    prix: 15,
    anecdote: "Cueillie à la main, à la surface de l'eau, seulement les jours où le vent et le soleil le permettent.",
  },
  {
    id: "champagne-krug-millesime",
    nom: "Une bouteille de champagne Krug millésimé",
    photo: `${BASE}photos/ca-coute-combien/champagne-krug-millesime.webp`,
    prix: 250,
  },
  {
    id: "riz-japonais-premium",
    nom: "Un sac de riz japonais premium (5 kg)",
    photo: `${BASE}photos/ca-coute-combien/riz-japonais-premium.webp`,
    prix: 40,
  },
  {
    id: "whisky-macallan-rare-cask",
    nom: "Une bouteille de whisky écossais Macallan, single malt haut de gamme",
    photo: `${BASE}photos/ca-coute-combien/whisky-macallan-rare-cask.webp`,
    prix: 350,
  },
  {
    id: "escargots-bourgogne-douzaine",
    nom: "Une douzaine d'escargots de Bourgogne, au restaurant",
    photo: `${BASE}photos/ca-coute-combien/escargots-bourgogne-douzaine.webp`,
    prix: 18,
  },
  {
    id: "caviar-oscietre",
    nom: "Un caviar Osciètre, les 30 grammes",
    photo: `${BASE}photos/ca-coute-combien/caviar-oscietre.webp`,
    prix: 150,
  },
  {
    id: "chocolat-noir-grand-cru",
    nom: "Une tablette de chocolat noir grand cru (100 g)",
    photo: `${BASE}photos/ca-coute-combien/chocolat-noir-grand-cru.webp`,
    prix: 12,
  },
  {
    id: "the-oolong-grand-cru",
    nom: "100 grammes de thé oolong grand cru",
    photo: `${BASE}photos/ca-coute-combien/the-oolong-grand-cru.webp`,
    prix: 35,
  },
  {
    id: "sel-himalaya-rose",
    nom: "500 grammes de sel rose de l'Himalaya artisanal",
    photo: `${BASE}photos/ca-coute-combien/sel-himalaya-rose.webp`,
    prix: 10,
  },
  {
    id: "gin-artisanal-premium",
    nom: "Une bouteille de gin artisanal premium",
    photo: `${BASE}photos/ca-coute-combien/gin-artisanal-premium.webp`,
    prix: 45,
  },
  {
    id: "rhum-vieux-agricole",
    nom: "Une bouteille de rhum vieux agricole, millésime 21 ans",
    photo: `${BASE}photos/ca-coute-combien/rhum-vieux-agricole.webp`,
    prix: 170,
  },
  {
    id: "orient-express-venise-londres",
    nom: "Un billet en cabine simple à bord du Venice Simplon-Orient-Express, Londres-Venise",
    photo: `${BASE}photos/ca-coute-combien/orient-express-venise-londres.webp`,
    prix: 3200,
    anecdote: "Des voitures des années 1920 restaurées au millimètre — smoking et robe de soirée exigés au dîner.",
  },
  {
    id: "croisiere-antarctique-semaine",
    nom: "Une croisière d'expédition d'une semaine en Antarctique, cabine standard",
    photo: `${BASE}photos/ca-coute-combien/croisiere-antarctique-semaine.webp`,
    prix: 8000,
  },
  {
    id: "suite-sous-marine-muraka",
    nom: "Une nuit dans la suite sous-marine The Muraka, au Conrad Maldives Rangali Island",
    photo: `${BASE}photos/ca-coute-combien/suite-sous-marine-muraka.webp`,
    prix: 50000,
    anecdote: "La première chambre sous-marine au monde : on dort à cinq mètres sous l'océan Indien, entouré de requins.",
  },
  {
    id: "safari-masai-mara-semaine",
    nom: "Un safari photo d'une semaine tout compris au Masaï Mara, au Kenya",
    photo: `${BASE}photos/ca-coute-combien/safari-masai-mara-semaine.webp`,
    prix: 4500,
  },
  {
    id: "trek-camp-base-everest",
    nom: "Un trek organisé jusqu'au camp de base de l'Everest, au Népal",
    photo: `${BASE}photos/ca-coute-combien/trek-camp-base-everest.webp`,
    prix: 4000,
  },
  {
    id: "passager-cargo-tour-du-monde",
    nom: "Un tour du monde en tant que passager à bord d'un porte-conteneurs",
    photo: `${BASE}photos/ca-coute-combien/passager-cargo-tour-du-monde.webp`,
    prix: 12000,
  },
  {
    id: "cage-requins-blancs-guadalupe",
    nom: "Une sortie de plusieurs jours en cage pour observer des requins blancs, à Isla Guadalupe",
    photo: `${BASE}photos/ca-coute-combien/cage-requins-blancs-guadalupe.webp`,
    prix: 1200,
  },
  {
    id: "vol-voltige-biplace",
    nom: "Un vol d'initiation à la voltige aérienne en biplan, place passager",
    photo: `${BASE}photos/ca-coute-combien/vol-voltige-biplace.webp`,
    prix: 250,
  },
  {
    id: "traversee-queen-mary-2",
    nom: "Une traversée transatlantique à bord du Queen Mary 2, cabine intérieure",
    photo: `${BASE}photos/ca-coute-combien/traversee-queen-mary-2.webp`,
    prix: 1800,
  },
  {
    id: "transsiberien-cabine-2e-classe",
    nom: "Un trajet Moscou-Vladivostok en Transsibérien, cabine de seconde classe",
    photo: `${BASE}photos/ca-coute-combien/transsiberien-cabine-2e-classe.webp`,
    prix: 700,
  },
  {
    id: "plongee-epave-apra-harbor",
    nom: "Une plongée d'exploration sur une épave, dans le port d'Apra, à Guam",
    photo: `${BASE}photos/ca-coute-combien/plongee-epave-apra-harbor.webp`,
    prix: 150,
  },
  {
    id: "caledonian-sleeper-cabine",
    nom: "Une nuit en cabine double à bord du train de nuit Caledonian Sleeper, Londres-Écosse",
    photo: `${BASE}photos/ca-coute-combien/caledonian-sleeper-cabine.webp`,
    prix: 200,
  },
  {
    id: "vol-zeppelin-touristique",
    nom: "Un vol touristique d'une heure à bord d'un dirigeable Zeppelin NT",
    photo: `${BASE}photos/ca-coute-combien/vol-zeppelin-touristique.webp`,
    prix: 400,
  },
  {
    id: "croisiere-nil-semaine",
    nom: "Une croisière d'une semaine sur le Nil, entre Louxor et Assouan",
    photo: `${BASE}photos/ca-coute-combien/croisiere-nil-semaine.webp`,
    prix: 1200,
  },
  {
    id: "vol-parabolique-apesanteur",
    nom: "Un vol parabolique en apesanteur, façon entraînement d'astronaute",
    photo: `${BASE}photos/ca-coute-combien/vol-parabolique-apesanteur.webp`,
    prix: 6000,
    anecdote: "Un avion de ligne entier dédié à la manœuvre, pour environ 22 secondes d'apesanteur par parabole.",
  },
  {
    id: "expedition-brise-glace-pole-nord",
    nom: "Une expédition en brise-glace jusqu'au Pôle Nord géographique",
    photo: `${BASE}photos/ca-coute-combien/expedition-brise-glace-pole-nord.webp`,
    prix: 30000,
    anecdote: "Le seul brise-glace nucléaire au monde à embarquer des touristes jusqu'au pôle Nord géographique.",
  },
  {
    id: "trek-patagonie-torres-del-paine",
    nom: "Un trek d'une semaine dans le parc Torres del Paine, en Patagonie",
    photo: `${BASE}photos/ca-coute-combien/trek-patagonie-torres-del-paine.webp`,
    prix: 2500,
  },
  {
    id: "nuit-refuge-kilimandjaro",
    nom: "Une nuit en refuge d'altitude lors de l'ascension du Kilimandjaro",
    photo: `${BASE}photos/ca-coute-combien/nuit-refuge-kilimandjaro.webp`,
    prix: 2200,
  },
  {
    id: "trek-gorilles-virunga",
    nom: "Un permis de trek pour observer les gorilles des montagnes, dans le massif des Virunga",
    photo: `${BASE}photos/ca-coute-combien/trek-gorilles-virunga.webp`,
    prix: 1500,
    anecdote: "Le permis donne droit à une heure exactement avec les gorilles : c'est lui qui finance leur protection.",
  },
  {
    id: "hydravion-fjords-alaska",
    nom: "Un tour en hydravion au-dessus des fjords d'Alaska",
    photo: `${BASE}photos/ca-coute-combien/hydravion-fjords-alaska.webp`,
    prix: 300,
  },
  {
    id: "plongee-grande-barriere-corail",
    nom: "Une sortie snorkeling d'une journée sur la Grande Barrière de corail, en Australie",
    photo: `${BASE}photos/ca-coute-combien/plongee-grande-barriere-corail.webp`,
    prix: 220,
  },
  {
    id: "helicoptere-grand-canyon",
    nom: "Un survol en hélicoptère du Grand Canyon et du barrage Hoover",
    photo: `${BASE}photos/ca-coute-combien/helicoptere-grand-canyon.webp`,
    prix: 280,
  },
  {
    id: "train-machu-picchu",
    nom: "Un aller-retour en train touristique jusqu'au Machu Picchu, au Pérou",
    photo: `${BASE}photos/ca-coute-combien/train-machu-picchu.webp`,
    prix: 150,
  },
  {
    id: "observation-baleines-reykjavik",
    nom: "Une sortie en bateau d'observation des baleines, au départ de Reykjavik",
    photo: `${BASE}photos/ca-coute-combien/observation-baleines-reykjavik.webp`,
    prix: 100,
  },
  {
    id: "saut-parachute-tandem",
    nom: "Un saut en parachute en tandem, à 4000 mètres d'altitude",
    photo: `${BASE}photos/ca-coute-combien/saut-parachute-tandem.webp`,
    prix: 300,
  },
  {
    id: "tableau-monet-meules",
    nom: "Un tableau de la série des Meules de Claude Monet, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/tableau-monet-meules.webp`,
    prix: 110700000,
    anecdote: "Adjugé en huit minutes d'enchères en 2019 : record absolu pour Monet.",
  },
  {
    id: "piece-double-eagle-1933",
    nom: "Une pièce d'or 1933 Double Eagle, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/piece-double-eagle-1933.webp`,
    prix: 18900000,
    anecdote: "Frappée puis jamais mise en circulation : en posséder une a longtemps été illégal aux États-Unis.",
  },
  {
    id: "manuscrit-codex-leicester",
    nom: "Une page manuscrite du Codex Leicester de Léonard de Vinci, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/manuscrit-codex-leicester.webp`,
    prix: 30800000,
  },
  {
    id: "bible-gutenberg",
    nom: "Une Bible de Gutenberg complète, l'un des livres les plus rares au monde",
    photo: `${BASE}photos/ca-coute-combien/bible-gutenberg.webp`,
    prix: 5400000,
    anecdote: "Le premier grand livre imprimé d'Occident : il en subsiste moins de cinquante exemplaires.",
  },
  {
    id: "violon-stradivarius-lady-blunt",
    nom: 'Le violon Stradivarius "Lady Blunt" de 1721, vente aux enchères',
    photo: `${BASE}photos/ca-coute-combien/violon-stradivarius-lady-blunt.webp`,
    prix: 15900000,
    anecdote: "Vendu en 2011 au profit des sinistrés du tsunami japonais — un Stradivarius quasi neuf de 1721.",
  },
  {
    id: "diamant-hope",
    nom: "Le diamant Hope, valeur d'assurance estimée",
    photo: `${BASE}photos/ca-coute-combien/diamant-hope.webp`,
    prix: 250000000,
  },
  {
    id: "commode-louis-xv-marqueterie",
    nom: "Une commode à marqueterie d'époque Louis XV, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/commode-louis-xv-marqueterie.webp`,
    prix: 450000,
  },
  {
    id: "ferrari-250-gto",
    nom: "Une Ferrari 250 GTO de 1962, vente privée entre collectionneurs",
    photo: `${BASE}photos/ca-coute-combien/ferrari-250-gto.webp`,
    prix: 70000000,
    anecdote: "Trente-six exemplaires construits : c'est simplement la voiture la plus chère du monde.",
  },
  {
    id: "montre-poche-tiffany-ancienne",
    nom: "Une montre à gousset ancienne Tiffany & Co. en or, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/montre-poche-tiffany-ancienne.webp`,
    prix: 18000,
  },
  {
    id: "collier-perles-naturelles",
    nom: "Un collier de perles fines naturelles anciennes, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/collier-perles-naturelles.webp`,
    prix: 2000000,
  },
  {
    id: "affiche-metropolis-1927",
    nom: "Une affiche originale du film Metropolis (1927), vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/affiche-metropolis-1927.webp`,
    prix: 690000,
  },
  {
    id: "squelette-trex-stan",
    nom: "Un squelette de Tyrannosaurus rex quasi complet, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/squelette-trex-stan.webp`,
    prix: 31800000,
    anecdote: "« Stan » est le fossile le plus cher jamais vendu — parti aux enchères en 2020, direction Abou Dhabi.",
  },
  {
    id: "meteorite-martienne",
    nom: "Un fragment de météorite martienne rare, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/meteorite-martienne.webp`,
    prix: 612500,
    anecdote: "Au gramme, plus chère que l'or : un morceau de Mars arraché par un impact, tombé sur Terre.",
  },
  {
    id: "tapis-persan-safavide",
    nom: "Un tapis persan safavide ancien en soie, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/tapis-persan-safavide.webp`,
    prix: 33700000,
  },
  {
    id: "vase-porcelaine-ming",
    nom: "Un vase en porcelaine de la dynastie Ming, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/vase-porcelaine-ming.webp`,
    prix: 5000000,
  },
  {
    id: "carte-waldseemuller",
    nom: "Un exemplaire de la carte de Waldseemüller (1507), premier document nommant l'Amérique",
    photo: `${BASE}photos/ca-coute-combien/carte-waldseemuller.webp`,
    prix: 10000000,
  },
  {
    id: "buste-romain-marbre",
    nom: "Un buste romain antique en marbre, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/buste-romain-marbre.webp`,
    prix: 600000,
  },
  {
    id: "sabre-japonais-ancien",
    nom: "Un sabre japonais ancien (tachi), signé par un maître forgeron",
    photo: `${BASE}photos/ca-coute-combien/sabre-japonais-ancien.webp`,
    prix: 150000,
  },
  {
    id: "poupee-porcelaine-ancienne",
    nom: "Une poupée ancienne en porcelaine (bébé français du XIXe siècle), vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/poupee-porcelaine-ancienne.webp`,
    prix: 180000,
  },
  {
    id: "voiture-miniature-hotwheels-rare",
    nom: "Une voiture miniature Hot Wheels ultra-rare, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/voiture-miniature-hotwheels-rare.webp`,
    prix: 150000,
  },
  {
    id: "guitare-acoustique-legendaire",
    nom: "Une guitare acoustique ayant appartenu à une légende du rock, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/guitare-acoustique-legendaire.webp`,
    prix: 6000000,
  },
  {
    id: "appareil-photo-leica-ancien",
    nom: "Un appareil photo Leica parmi les tout premiers exemplaires produits, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/appareil-photo-leica-ancien.webp`,
    prix: 2800000,
  },
  {
    id: "machine-a-ecrire-ecrivain-celebre",
    nom: "Une machine à écrire ayant appartenu à un écrivain célèbre, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/machine-a-ecrire-ecrivain-celebre.webp`,
    prix: 90000,
  },
  {
    id: "photographie-daguerreotype-ancienne",
    nom: "Un daguerréotype rare du XIXe siècle, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/photographie-daguerreotype-ancienne.webp`,
    prix: 120000,
  },
  {
    id: "sceau-imperial-jade-chinois",
    nom: "Un sceau impérial chinois en jade, dynastie Qing, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/sceau-imperial-jade-chinois.webp`,
    prix: 21000000,
  },
  {
    id: "puce-nvidia-h100",
    nom: "Une puce Nvidia H100, processeur graphique pour l'intelligence artificielle",
    photo: `${BASE}photos/ca-coute-combien/puce-nvidia-h100.webp`,
    prix: 30000,
    anecdote: "La ruée vers l'IA en a fait l'objet de toutes les pénuries : elle s'est revendue bien au-dessus du tarif.",
  },
  {
    id: "ordinateur-quantique-ibm",
    nom: "Un ordinateur quantique IBM Quantum System One",
    photo: `${BASE}photos/ca-coute-combien/ordinateur-quantique-ibm.webp`,
    prix: 15000000,
  },
  {
    id: "supercalculateur-cray-1",
    nom: "Un supercalculateur Cray-1, prix de lancement (1977)",
    photo: `${BASE}photos/ca-coute-combien/supercalculateur-cray-1.webp`,
    prix: 8860000,
  },
  {
    id: "premier-iphone-2007",
    nom: "Le tout premier iPhone (2007), prix de lancement du modèle 8 Go",
    photo: `${BASE}photos/ca-coute-combien/premier-iphone-2007.webp`,
    prix: 599,
    anecdote: "C'est son prix de lancement en 2007 — scellé en boîte, il s'arrache aujourd'hui à plus de 50 000 €.",
  },
  {
    id: "ibm-pc-5150",
    nom: "Un IBM PC 5150 (1981), prix de lancement de la configuration de base",
    photo: `${BASE}photos/ca-coute-combien/ibm-pc-5150.webp`,
    prix: 1565,
  },
  {
    id: "machine-enigma-encheres",
    nom: "Une machine Enigma allemande de la Seconde Guerre mondiale, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/machine-enigma-encheres.webp`,
    prix: 437000,
    anecdote: "La machine de chiffrement du IIIᵉ Reich : la plupart ont été détruites, chaque survivante est un trésor.",
  },
  {
    id: "apple-1-carte-mere",
    nom: "Une carte-mère Apple I fonctionnelle de 1976, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/apple-1-carte-mere.webp`,
    prix: 400000,
    anecdote: "Environ deux cents exemplaires, assemblés à la main par Steve Wozniak dans un garage.",
  },
  {
    id: "robot-chien-aibo",
    nom: "Un robot chien Sony Aibo, dernière génération",
    photo: `${BASE}photos/ca-coute-combien/robot-chien-aibo.webp`,
    prix: 2900,
  },
  {
    id: "casque-vr-haut-de-gamme",
    nom: "Un casque de réalité virtuelle haut de gamme",
    photo: `${BASE}photos/ca-coute-combien/casque-vr-haut-de-gamme.webp`,
    prix: 3499,
  },
  {
    id: "robot-chirurgical-davinci",
    nom: "Un robot chirurgical assisté par ordinateur, type Da Vinci",
    photo: `${BASE}photos/ca-coute-combien/robot-chirurgical-davinci.webp`,
    prix: 2000000,
  },
  {
    id: "drone-cartographie-rtk",
    nom: "Un drone professionnel de cartographie RTK",
    photo: `${BASE}photos/ca-coute-combien/drone-cartographie-rtk.webp`,
    prix: 13000,
  },
  {
    id: "scanner-irm-hospitalier",
    nom: "Un scanner IRM (imagerie par résonance magnétique) hospitalier",
    photo: `${BASE}photos/ca-coute-combien/scanner-irm-hospitalier.webp`,
    prix: 1500000,
    anecdote: "Le cœur de la machine est un aimant supraconducteur baigné d'hélium liquide à -269 °C.",
  },
  {
    id: "microscope-electronique-balayage",
    nom: "Un microscope électronique à balayage de laboratoire",
    photo: `${BASE}photos/ca-coute-combien/microscope-electronique-balayage.webp`,
    prix: 250000,
  },
  {
    id: "drone-reconnaissance-militaire",
    nom: "Un drone de reconnaissance militaire, coût unitaire (type MQ-9 Reaper)",
    photo: `${BASE}photos/ca-coute-combien/drone-reconnaissance-militaire.webp`,
    prix: 16000000,
  },
  {
    id: "nanosatellite-cubesat",
    nom: "Un nanosatellite CubeSat, construction et lancement compris",
    photo: `${BASE}photos/ca-coute-combien/nanosatellite-cubesat.webp`,
    prix: 300000,
  },
  {
    id: "bras-robotique-industriel",
    nom: "Un bras robotique industriel de précision",
    photo: `${BASE}photos/ca-coute-combien/bras-robotique-industriel.webp`,
    prix: 80000,
  },
  {
    id: "telescope-amateur-haut-de-gamme",
    nom: "Un télescope amateur haut de gamme",
    photo: `${BASE}photos/ca-coute-combien/telescope-amateur-haut-de-gamme.webp`,
    prix: 5000,
  },
  {
    id: "station-travail-mac-pro",
    nom: "Une station de travail professionnelle (type Mac Pro)",
    photo: `${BASE}photos/ca-coute-combien/station-travail-mac-pro.webp`,
    prix: 7000,
  },
  {
    id: "imprimante-3d-grand-public",
    nom: "Une imprimante 3D grand public (type Prusa)",
    photo: `${BASE}photos/ca-coute-combien/imprimante-3d-grand-public.webp`,
    prix: 800,
  },
  {
    id: "processeur-grand-public",
    nom: "Un processeur (CPU) grand public haut de gamme",
    photo: `${BASE}photos/ca-coute-combien/processeur-grand-public.webp`,
    prix: 800,
  },
  {
    id: "macintosh-128k-1984",
    nom: "Un Macintosh 128K (1984), prix de lancement",
    photo: `${BASE}photos/ca-coute-combien/macintosh-128k-1984.webp`,
    prix: 2495,
  },
  {
    id: "imprimante-3d-industrielle",
    nom: "Une imprimante 3D industrielle professionnelle",
    photo: `${BASE}photos/ca-coute-combien/imprimante-3d-industrielle.webp`,
    prix: 100000,
  },
  {
    id: "supercalculateur-frontier",
    nom: "Le supercalculateur Frontier (Oak Ridge), coût de construction",
    photo: `${BASE}photos/ca-coute-combien/supercalculateur-frontier.webp`,
    prix: 600000000,
  },
  {
    id: "falcon9-premier-etage-reutilisable",
    nom: "Un premier étage réutilisable de fusée Falcon 9, coût de fabrication",
    photo: `${BASE}photos/ca-coute-combien/falcon9-premier-etage-reutilisable.webp`,
    prix: 15000000,
    anecdote: "Réutilisable une vingtaine de fois : c'est cette fusée qui a cassé les prix de l'accès à l'espace.",
  },
  {
    id: "robot-quadrupede-securite",
    nom: "Un robot quadrupède commercial pour usages professionnels (type Boston Dynamics Spot)",
    photo: `${BASE}photos/ca-coute-combien/robot-quadrupede-securite.webp`,
    prix: 74500,
  },
  {
    id: "robe-marilyn-monroe-seven-year-itch",
    nom: "La robe blanche portée par Marilyn Monroe dans Sept Ans de réflexion, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/robe-marilyn-monroe-seven-year-itch.webp`,
    prix: 5520000,
    anecdote: "LA robe blanche du métro new-yorkais — l'un des costumes les plus chers jamais adjugés.",
  },
  {
    id: "chaussures-rubis-dorothy-oz",
    nom: "Les escarpins rubis portés par Judy Garland dans Le Magicien d'Oz, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/chaussures-rubis-dorothy-oz.webp`,
    prix: 28000000,
    anecdote: "Les souliers du « Magicien d'Oz » : record absolu pour un objet de cinéma, volés puis retrouvés en 2018.",
  },
  {
    id: "sac-hermes-birkin-himalaya-diamants",
    nom: "Un sac Hermès Birkin Himalaya en crocodile serti de diamants, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/sac-hermes-birkin-himalaya-diamants.webp`,
    prix: 380000,
  },
  {
    id: "costume-dark-vador-promotionnel",
    nom: "Un costume promotionnel de Dark Vador des studios Star Wars, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/costume-dark-vador-promotionnel.webp`,
    prix: 287500,
  },
  {
    id: "costume-superman-christopher-reeve",
    nom: "Le costume complet de Superman porté par Christopher Reeve dans le film original, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/costume-superman-christopher-reeve.webp`,
    prix: 350000,
  },
  {
    id: "gant-michael-jackson-moonwalk",
    nom: "Le gant pailleté porté par Michael Jackson lors de sa performance du moonwalk, vente aux enchères",
    photo: `${BASE}photos/ca-coute-combien/gant-michael-jackson-moonwalk.webp`,
    prix: 420000,
    anecdote: "Le gant blanc du tout premier moonwalk, en 1983 — un seul gant, brodé de strass.",
  },
  {
    id: "robe-mariee-haute-couture-elie-saab",
    nom: "Une robe de mariée haute couture sur mesure, chez un grand couturier comme Elie Saab",
    photo: `${BASE}photos/ca-coute-combien/robe-mariee-haute-couture-elie-saab.webp`,
    prix: 300000,
  },
  {
    id: "costume-savile-row-bespoke",
    nom: "Un costume bespoke chez un tailleur de Savile Row, à Londres",
    photo: `${BASE}photos/ca-coute-combien/costume-savile-row-bespoke.webp`,
    prix: 6000,
  },
  {
    id: "veste-chanel-tweed-vintage",
    nom: "Une veste vintage en tweed Chanel des années 1960, seconde main authentifiée",
    photo: `${BASE}photos/ca-coute-combien/veste-chanel-tweed-vintage.webp`,
    prix: 4500,
  },
  {
    id: "manteau-vison-vintage",
    nom: "Un manteau en vison vintage restauré",
    photo: `${BASE}photos/ca-coute-combien/manteau-vison-vintage.webp`,
    prix: 3000,
  },
  {
    id: "kimono-soie-vintage-japonais",
    nom: "Un kimono de soie vintage japonais brodé à la main",
    photo: `${BASE}photos/ca-coute-combien/kimono-soie-vintage-japonais.webp`,
    prix: 1200,
  },
  {
    id: "escarpins-manolo-blahnik-hangisi",
    nom: "Une paire d'escarpins Manolo Blahnik Hangisi ornés d'une boucle en cristal",
    photo: `${BASE}photos/ca-coute-combien/escarpins-manolo-blahnik-hangisi.webp`,
    prix: 1000,
  },
  {
    id: "tailleur-ysl-le-smoking-vintage",
    nom: "Un tailleur-pantalon Yves Saint Laurent Le Smoking vintage",
    photo: `${BASE}photos/ca-coute-combien/tailleur-ysl-le-smoking-vintage.webp`,
    prix: 3500,
  },
  {
    id: "gants-longs-soiree-vintage",
    nom: "Une paire de gants longs de soirée vintage",
    photo: `${BASE}photos/ca-coute-combien/gants-longs-soiree-vintage.webp`,
    prix: 300,
  },
  {
    id: "carre-hermes-soie",
    nom: "Un carré de soie Hermès, modèle emblématique",
    photo: `${BASE}photos/ca-coute-combien/carre-hermes-soie.webp`,
    prix: 520,
  },
  {
    id: "parfum-chanel-no5",
    nom: "Un flacon de parfum Chanel N°5, format classique",
    photo: `${BASE}photos/ca-coute-combien/parfum-chanel-no5.webp`,
    prix: 150,
  },
  {
    id: "cravate-hermes-soie",
    nom: "Une cravate en soie Hermès imprimée",
    photo: `${BASE}photos/ca-coute-combien/cravate-hermes-soie.webp`,
    prix: 230,
  },
  {
    id: "chale-pashmina-brode",
    nom: "Un châle en pashmina brodé main, cachemire fin",
    photo: `${BASE}photos/ca-coute-combien/chale-pashmina-brode.webp`,
    prix: 400,
  },
  {
    id: "qipao-soie-vintage",
    nom: "Un qipao (cheongsam) vintage en soie, pièce d'époque des années 1930",
    photo: `${BASE}photos/ca-coute-combien/qipao-soie-vintage.webp`,
    prix: 600,
  },
  {
    id: "robe-flamenco-artisanale",
    nom: "Une robe de flamenco traditionnelle, confection artisanale espagnole",
    photo: `${BASE}photos/ca-coute-combien/robe-flamenco-artisanale.webp`,
    prix: 800,
  },
  {
    id: "chapeau-feutre-italien-luxe",
    nom: "Un chapeau en feutre italien de luxe, façon Borsalino",
    photo: `${BASE}photos/ca-coute-combien/chapeau-feutre-italien-luxe.webp`,
    prix: 400,
  },
  {
    id: "chapeau-panama-montecristi",
    nom: "Un authentique chapeau Panama Montecristi, tissage fin",
    photo: `${BASE}photos/ca-coute-combien/chapeau-panama-montecristi.webp`,
    prix: 2000,
    anecdote: "Plusieurs mois de tissage à la main : la finesse se compte en nombre de points par pouce.",
  },
  {
    id: "ensemble-smoking-ysl-musee",
    nom: "Un ensemble smoking haute couture Yves Saint Laurent, pièce de musée",
    photo: `${BASE}photos/ca-coute-combien/ensemble-smoking-ysl-musee.webp`,
    prix: 40000,
  },
  {
    id: "lunettes-rayban-vintage-collector",
    nom: "Une paire de lunettes de soleil Ray-Ban vintage de collection",
    photo: `${BASE}photos/ca-coute-combien/lunettes-rayban-vintage-collector.webp`,
    prix: 250,
  },
  {
    id: "robe-soiree-ysl-1971-musee",
    nom: "Une robe du soir Yves Saint Laurent de 1971, pièce de musée",
    photo: `${BASE}photos/ca-coute-combien/robe-soiree-ysl-1971-musee.webp`,
    prix: 60000,
  },
];
