export interface PhotoCredit {
  id: string;
  author: string;
  license: string;
  sourceUrl: string;
}

export const PHOTO_CREDITS: PhotoCredit[] = [
  {
    id: "ticket-metro-paris",
    author: "Tangopaso",
    license: "Domaine public",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ticket_metro_Paris_recto_%26_verso.jpg",
  },
  {
    id: "pizza-napoli",
    author: "Fabryx98",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pizza-napoletana.jpg",
  },
  {
    id: "big-mac",
    author: "rob_rob2001",
    license: "CC BY-SA 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Big_Mac_47.jpg",
  },
  {
    id: "cabane-arbre",
    author: "Mgwalter",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cashie_River_Treehouses_Windsor,_NC,_USA.jpg",
  },
  {
    id: "san-marco-cafe",
    author: "Tiia Monto",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Piazza_San_Marco,_Venice.jpg",
  },
  {
    id: "icehotel",
    author: "Stephan Herz",
    license: "CC BY 2.5",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Icehotel-se-04.JPG",
  },
  {
    id: "monaco-gp-tribune",
    author: "Abxbay",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Monaco_preparing_for_grand_prix.JPG",
  },
  {
    id: "truffe-alba",
    author: "Mortazavifar",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:White-truffle-pic.jpg",
  },
  {
    id: "burj-al-arab",
    author: "Yacine Hary",
    license: "CC BY 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Burj_Al_Arab_and_Jumeirah_Beach_(9601659067).jpg",
  },
  {
    id: "yacht-saint-tropez",
    author: "dronepicr",
    license: "CC BY 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Yachts_at_the_port_of_Saint-Tropez,_France_(52723273867).jpg",
  },
  {
    id: "ticket-eiffel-sommet",
    author: "Fidelio",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:View_from_top_of_Eiffel_Tower.JPG",
  },
  {
    id: "boeuf-kobe",
    author: "Ceeseven",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Beef_Steak_on_Sizzling_Plate.jpg",
  },
  {
    id: "capsule-hotel-tokyo",
    author: "Michael",
    license: "CC BY 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:CAPSULE_HOTEL,_TOKYO.jpg",
  },
  {
    id: "gondole-venise",
    author: "Peter K Burian",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Gondola_on_the_Grand_Canal,_Venice,_Italy.jpg",
  },
  {
    id: "lego-minifigure",
    author: "Nam Hy Hoàng Phong",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:LEGO_minifigures_display_case.jpg",
  },
  {
    id: "champagne-dom-perignon",
    author: "giulio nepi",
    license: "CC BY 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Champagne_Dom_Perignon.jpg",
  },
  {
    id: "wimbledon-centre-court",
    author: "GATORFAN2525",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Wimbledon_Centre_Court_(May_15,_2019).jpg",
  },
  {
    id: "montgolfiere-cappadoce",
    author: "Mygeorgianguide",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Hot_air_balloons_in_Cappadocia.jpg",
  },
  {
    id: "rolex-submariner",
    author: "foeoc kannilc",
    license: "CC BY 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Rolex_Submariner_diving_watch.jpg",
  },
  {
    id: "colisee-rome",
    author: "Podluzhnaya",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Colosseum,_Rome.JPG",
  },
  {
    id: "huitres-brasserie",
    author: "George Pollard",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bluff_oysters_on_ice.jpg",
  },
  {
    id: "louvre-pyramide",
    author: "Briqus Orven Rémi",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:La_Pyramide_du_Louvre.JPG",
  },
  {
    id: "helico-manhattan",
    author: "Andy C",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Manhattan_Heliport_Helicopter.JPG",
  },
  {
    id: "cronut-nyc",
    author: "cumi&ciki",
    license: "CC BY 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cronut.jpg",
  },
  {
    id: "sneakers-air-jordan",
    author: "Jacek Halicki",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2023_Buty_Nike_Air_Jordan.jpg",
  },
  {
    id: "plein-gpl",
    author: "Emilius123",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bft_Groß-Rohrheim_LPG.png",
  },
  {
    id: "carte-grise-citadine",
    author: "originaux préfecture et assurance",
    license: "Domaine public",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Permis_carte_grise_et_verte_france.JPG",
  },
  {
    id: "ramonage-cheminee",
    author: "Thunk (en.wikipedia)",
    license: "Domaine public",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Chimney_sweep_modern.jpg",
  },
  {
    id: "place-creche-mois",
    author: "Joachim Kohler",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Kinderkrippe_Grünschnabel,_Kirchstr._21_in_Detern_(2023).jpg",
  },
  {
    id: "defile-mode-place",
    author: "David Shankbone",
    license: "CC BY 2.5",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Catwalk_by_David_Shankbone.jpg",
  },
  {
    id: "nuit-refuge-garde",
    author: "Florian Pépellin",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Refuge_et_Pic_de_l%27Étendard_(Savoie).JPG",
  },
  {
    id: "laverie-automatique-mois",
    author: "Baron Maddock",
    license: "CC BY 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:A_row_of_Wascomat_WLD_20_and_45_lb_washers_at_Dulles_Park_Coin_Laundry.jpg",
  },
  {
    id: "reparation-ecran-smartphone",
    author: "TCY",
    license: "CC BY 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Distributeur_automatique_WeFix,_gare_d%27Angers.jpg",
  },
  {
    id: "demenagement-studio",
    author: "Johann H. Addicks",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Umzugslift.jpg",
  },
  {
    id: "consultation-osteopathe",
    author: "Ugo Demaria",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ugo_demaria-osteopata_asti-centro-riabilitazione-medico-hastafisio-15.jpg",
  },
  {
    id: "forfait-mobile-haut-gamme-mois",
    author: "Dennis Cortés",
    license: "CC0 1.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Black_smartphone_in_hand_(Unsplash).jpg",
  },
  {
    id: "cinema-4dx-place",
    author: "Wolfmann",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:4DX_seats_in_cinema_(motion_and_environmental_effects_synced_with_the_on-screen_action)_bench_rows_in_a_movie_theater_hall_Kinostoler_kinosal_Kilden_kino_Tønsberg,_Norway_2023_IMG_7849.jpg",
  },
  {
    id: "nuit-yourte",
    author: "Rick Obst",
    license: "CC BY 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Basic_Yurt_Interior_in_Beverly_Beach_State_Park.jpg",
  },
  {
    id: "conduite-accompagnee-forfait",
    author: "TudorTulok",
    license: "CC0 1.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Compact_Learner_Car_Parked_in_UK_Park.jpg",
  },
  {
    id: "parking-sous-sol-mensuel",
    author: "Daniel Case",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Interior_of_Concordia_University_underground_parking_garage,_Montreal,_QC.jpg",
  },
  {
    id: "box-streaming-sportif-mois",
    author: "Nenad Stojković",
    license: "CC BY 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Person_uses_remote_control_to_watch_TV_at_home.jpg",
  },
  {
    id: "carte-identite-renouvellement",
    author: "Ministère de l'Intérieur",
    license: "Domaine public",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Carte_identité_électronique_française_(2021,_recto).png",
  },
  {
    id: "timbre-lettre-prioritaire",
    author: "JoF (Jochen Frey)",
    license: "CC BY 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Boîte_murale_jaune_de_La_Poste.jpg",
  },
  {
    id: "amende-stationnement-genant",
    author: "יעקב",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:ParkingTicketTA535.jpg",
  },
  {
    id: "sac-pellets-poele",
    author: "Ralph Oesker",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Wood_pellets_in_a_reservoir.jpg",
  },
  {
    id: "detartrage-dentiste",
    author: "Walter Siegmund",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tooth_scaling_9301.JPG",
  },
  {
    id: "data-illimitee-etranger-semaine",
    author: "Raimond Spekking",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Full-size_SIM_card_with_PIN_and_PUK-2459.jpg",
  },
  {
    id: "salon-professionnel-place",
    author: "Jeff Morey",
    license: "CC BY-SA 2.5",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:IGC_Show_trade_show_floor_Aug_2016.jpg",
  },
  {
    id: "revision-complete-voiture",
    author: "Nenad Stojković",
    license: "CC BY 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Car_mechanic_worker_repairing_suspension_of_lifted_automobile_at_auto_repair_garage_shop.jpg",
  },
];
